config/routes.rb
 Rails.application.routes.draw do
  root to: "questions#new"
  resources :questions, only: [:new, :index, :create, :destroy]
  devise_for :users
  resources :users, only: [:index, :show, :update, :edit] do
    member do
      get "show_following"
      get "show_followers"
    end
  end
  resources :follows, only: [:index, :create, :destroy]
  resources :answers, only: [:new, :create, :destroy]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :pictures, as: :imageable, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :users, through: :genre_users, inverse_of: :genre
  has_many :genre_users, dependent: :nullify
end

app/models/genre_user.rb
class GenreUser < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true, inverse_of: :picture
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :pictures, as: :imageable, dependent: :destroy
  default_scope -> { order(created_at: :desc) }

  def feed_answers
    answer_ids = "SELECT id FROM answers WHERE  question_id = :question_id"
    Answer.where("id IN (#{answer_ids})", question_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :genres, through: :genre_users, inverse_of: :user
  has_many :genre_users, dependent: :destroy

  mount_uploader :profile_image, ProfileUploader
  mount_uploader :cover_image, CoverUploader

  acts_as_followable
  acts_as_follower

  acts_as_taggable_on :skills, :interests

  def feed
    following_ids = "SELECT followable_id FROM follows WHERE follower_id = :user_id"
    Question.where("user_id IN (#{following_ids})", user_id: id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def new
    @question = Question.find(params[:id])
    @answer = current_user.answers.build(question_id: @question.id)
    @feed_answers_items = @question.feed_answers
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:success] = "Your answer posted!"
      redirect_to request.referrer || root_url
    else
      flash[:error] = "Your answer NOT posted...!!"
      render 'answers/new'
    end
  end

  def destroy
    if current_user
      @answer = current_user.answers.find_by(id: params[:id])
      @answer.destroy
      flash[:success] = "Answer deleted"
      redirect_to request.referrer || root_url
    else
      flash[:error] = "Answer NOT deleted...!"
      redirect_to roo_url
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :user_id, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:alias_name, :name])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow

  def create
    current_user.follow(@follow)
    redirect_to @follow
  end

  def destroy
    current_user.stop_following(@follow)
    redirect_to @follow
  end

  private

  def set_follow
    @follow = User.find(params[:followable_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, :set_question

  def new
  end

  def index
    @feed_items = current_user.feed
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:success] = "Question created!"
      redirect_to root_url
    else
      flash[:error] = "Question NOT created...!"
      render 'questions/index'
    end
  end

  def destroy
    if current_user
      @question = current_user.questions.find_by(id: params[:id])
      @question.destroy
      flash[:success] = "Question deleted"
      redirect_to request.referrer || root_url
    else
      flash[:error] = "Question NOT deleted...!"
      redirect_to root_url
    end
  end

  private

  def question_params
    params.require(:question).permit(:content, :user_id)
  end

  def set_question
    @user = User.find(current_user.id)
    @question = current_user.questions.build(user_id: @user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: :index

  def index
    @users = User.all
  end

  def show
    @questions = Question.where(user_id: @user.id)
    if signed_in?
      @follow_user = current_user.follows.build(followable_id: @user.id, follower_id: :current_user)
      @unfollow_user = current_user.follows.find_by(followable_id: @user.id)
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated!"
      redirect_to action: :edit
    else
      flash.now[:error] = "Profile update failed "
      render :edit
    end
  end

  def show_following
    @title = "Following"
    @users = @user.all_following
    render "show_follow"
  end

  def show_followers
    @title = "Followers"
    @users = @user.followers
    render "show_follow"
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :alias_name,
      :name,
      :profile_image,
      :cover_image,
      :area,
      :introduce,
      :skill_list,
      :interest_list,
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
  { success: "alert-success", error: "alert-danger",
    alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |flash_type, message|
      concat(
        content_tag(:div, message, class: "alert alert-dismissable #{bootstrap_class_for(flash_type)} fade in") do
          concat(
            content_tag(:button, class: "close", data: { dismiss: "alert" }) do
              concat content_tag(:span, "&times;".html_safe)
            end
          )
          concat message
        end
      )
    end
  end
end

app/views/answers/_answer.html.erb
<div class="row">
  <div class="col-md-2">
    <%= image_tag answer.user.profile_image, size: 80 %>
  </div>
  <div class="col-md-10">
    <h3><%= link_to answer.user.name, answer.user %>@<%= answer.user.alias_name %></h3>
    <div>
      <%= answer.content %>
    </div>

    <div class="d-flex align-items-center">
      <p class="form-text text-muted p-2">Posted <%= time_ago_in_words(answer.created_at) %> ago.</p>
      <% if current_user == answer.user %>
        <%= link_to "delete", answer_path(answer), method: :delete, data:{ confirm: "You sure?" }, class: "btn btn-outline-danger pull-right ml-auto p-2"%>
      <% end %>
    </div>
  </div>
</div>
</br>

app/views/answers/new.html.erb
<h1><%= @question.user.name %>'s Question</h1>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= image_tag @question.user.profile_image, size: 90 %></br>
    <h3><%= link_to @question.user.name, @question.user %>@<%= @question.user.alias_name %></h3>
    <div class="field">
      <%= @question.content %>
        <p class="form-text text-muted">Posted <%= time_ago_in_words(@question.created_at) %> ago.</p>
      </div>

      <h3>Your Answer</h3>
      <%= form_for(@answer) do |f| %>
        <div class="field">
          <%= f.text_area :content, placeholder: "Post your answer !",class: "form-control form-control-lg" %>
          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :question_id %>
        </div>
          <%= f.submit "Post answer", class: "btn btn-lg btn-primary btn-block" %>
      <% end %>
  <hr></hr>
    <%= render partial: 'shared/feed_answers', locals: { feed_answers_items: @feed_answers_items } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ask Skill Holders</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <div class="header bg-dark">
      <div class="container">
        <%= link_to "Ask Skill Holders", root_path, id: "logo" %>
        <nav>
          <ul class="nav justify-content-end">
            <% if signed_in? %>
              <li class="nav-items"><%= link_to "Home", root_path %></li>
              <li class="nav-items"><%= link_to "AskQuestion", new_question_path %></li>
              <li class="nav-items"><%= link_to "AnswerQuestons", questions_path %></li>
              <li class="nav-items"><%= link_to "FindUsers", users_path %></li>
              <li class="nav-items"><%= link_to "MyProfile", current_user %></li>
              <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Setting
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                  <button class="dropdown-item" type="button"><%= link_to "UpdateMyProfile", edit_user_path(current_user) %></button>
                  <button class="dropdown-item" type="button"><%= link_to "Setting", edit_user_registration_path(current_user) %></button>
                  <button class="dropdown-item" type="button"><%= link_to "SignOut", destroy_user_session_path, method: "delete" %></button>
                </div>
              </div>
            <% else %>
              <li class="nav-items"><%= link_to "About"  %></li>
              <li class="nav-items"><%= link_to "SignIn", new_user_session_path, class: "btn btn-lg btn-primary" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
      <div class="container wrapper">
        <% flash_messages %>
        <%= yield %>
        <div class="push"></div>
      </div>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="col-md-9">
  <div calss="row">
    <span class="user_profile_image">
      <%= image_tag question.user.profile_image, size: 80 %>
    </span>
    <h3><%= link_to question.user.name, question.user %>@<%= question.user.alias_name %></h3>
    <span class="content">
      <%= question.content %>
    </span>
      <div class="d-flex align-items-center">
        <p class="form-text text-muted p-2">Posted <%= time_ago_in_words(question.created_at) %> ago.</p>
        <% if current_user == question.user %>
          <%= link_to "See more", { controller: "answers", action: "new", id: question.id }, class: "btn btn-outline-success pull-right ml-auto p-2" %>
          <%= link_to "Delete", question_path(question), method: :delete, data:{ confirm: "You sure?" }, class: "btn btn-outline-danger pull-right ml-auto p-2" %>
        <% else %>
          <%= link_to "Answer", { controller: "answers", action: "new", id: question.id }, class: "btn btn-outline-success  ml-auto p-2" %>
        <% end %>
      </div>

  </div>
</div>

app/views/questions/index.html.erb
<h1>Answer Questions</h1>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <% if @user.follow_count == 0 %>
      <h2>You are following No One...</h2>
      <%= link_to "Let's Find Users to Follow !", users_path, class: "btn btn-lg btn-primary btn-block" %>
    <% else %>
      <div class="feeds">
        <%= render partial: 'shared/feed', locals: { feed_items: @feed_items } %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h1>Ask questions and resolve your problems in life</h1>
<h2>Hints to Ask Questions</h2>
<%= render partial: 'shared/question_form', locals: { question: @question } %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%= render feed_items %>

app/views/shared/_feed_answers.html.erb
<%= render feed_answers_items %>

app/views/shared/_question_form.html.erb
<div class="col-md-8 offset-md-2">
  <%= form_for(question, as: :question) do |f| %>
    <div class="field">
      <%= f.text_area :content, class: "form-control form-control-lg", placeholder: "Ask Question Now !" %>
      <%= f.hidden_field :user_id %>
    </div>
    <%= f.submit "Ask Question", class: "btn btn-lg btn-primary btn-block" %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<p><%= link_to "#{@user.follow_count} following", show_following_user_path, class: "font-weight-bold" %></p>
<p><%= link_to "#{@user.followers_count} followers", show_followers_user_path, class: "font-weight-bold" %><p>

app/views/shared/_user_info.html.erb
  <a href="<%= user_path(current_user) %>" class="user_profile_image">
    <%= image_tag user.profile_image, size: 70 %>
  </a>
  <div class="user_name">
    <h1>
      <%= current_user.name %>
    </h1>
    <div>
      @ <%= user.alias_name %>
    </div>
  </div>
  <span>
    <%= link_to "view my profile", current_user %>
  </span>

app/views/users/_follow.html.erb
<%= form_for(@follow_user) do |f| %>
  <%= hidden_field_tag :followable_id, @user.id %>
  <%= f.submit "Follow", class: "btn btn-outline-success" %>
<% end %>

app/views/users/_follow_form.html.erb
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'users/unfollow' %>
  <% else %>
    <%= render 'users/follow' %>
  <% end %>
  </div>

app/views/users/_listup_users.html.erb
<% @users.each do |user| %>
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <span class="user_profile_image">
        <%= image_tag user.profile_image, size: 90 %>
      </span>

      <h3><%= link_to user.name, user %>@<%= user.alias_name %></h3>

      <span class="content">
        <%= user.introduce %>
      </span>
    </div>
  </div>
<% end %>

app/views/users/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="label label-primary"><%= tag %></span>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(@unfollow_user, html: { method: :delete }) do |f| %>
  <%= hidden_field_tag :followable_id, @user.id %>
  <%= f.submit "Unfollow", class:"btn btn-outline-danger" %>
<% end %>

app/views/users/edit.html.erb
<%= provide(:tiele, "Update your profile") %>
<h1>Update <%= @user.name %>'s Profile</h1>

  <%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

      <h3><%= f.label :cover_image %></h3>
      <%= image_tag @user.cover_image.url if @user.cover_image? %>
      <%= f.file_field :cover_image %></br>

      <h3><%= f.label :profile_image %></h3>
      <%= image_tag @user.profile_image.url if @user.profile_image? %>
      <%= f.file_field :profile_image %></br>

      <div class="form-group">
        <h3><%= f.label :name %></h3>
        <%= f.text_field :name, class: "form-control" %></br>
      </div>

      <div class="form-group">
        <h3><%= f.label :email %></h3>
        <%= f.text_field :email, class: "form-control" %></br>
      </div>

      <div class="form-group">
        <h3><%= f.label :area%></h3>
        <%= f.text_field :area, class: "form-control" %></br>
      </div>

      <div class="form-group">
        <h3><%= f.label :introduce %></h3>
        <%= f.text_area :introduce, class: "form-control" %></br>
      </div>

      <div class="form-group">
        <h3><%= f.label :skill_list, "Skills" %></h3>
        <%= text_field_tag 'user[skill_list]', @user.skill_list.join(','), class: "form-control" %></br>
      </div>

      <div class="form-group">
        <h3><%= f.label :interest_list, "Interests" %></h3>
        <%= text_field_tag 'user[interest_list]', @user.interest_list.join(','), class: "form-control" %></br>
      </div>

        <%= f.submit "Update Profile", class: "btn btn-primary btn-lg btn-block" %></br>
  <% end %>

app/views/users/index.html.erb
<h1>Find Users</h1>
<%= render partial: 'users/listup_users', locals: { users: @users } %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<p><%= image_tag @user.cover_image, class: "cover_image" %></p>
<p><%= image_tag @user.profile_image, class: "profile_image" %></p>

<div class="row">
  <div class="col-md-3">
    <h1><%= @user.name %> @<%= @user.alias_name %></h1>
    <h3>Area:<%= @user.area %></h3>
    <p><%= @user.introduce %></p>

    <h3>Skills<%= render 'users/tag_list', tag_list: @user.skill_list %></h3>
    <h3>Interests<%= render 'users/tag_list', tag_list: @user.interest_list %></h3>

    <h4><%= render 'shared/stats' %></h4>

      <% if current_user == @user %>
        <p><%= link_to "Update profile", edit_user_path(current_user), class: "btn btn-outline-secondary" %></p>
      <% end %>
    <% if signed_in? %>
      <%= render 'users/follow_form' unless current_user.id == @user.id %>
    <% end %>
  </div>

  <div class="col-md-9">
    <h2><%= @user.name %>'s Questions</h2>


    <ol>
      <%= render @questions %>
    </ol>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
  <% if @users.any? %>
    <%= render partial: 'users/listup_users', locals: { users: @users } %>
  <% end %>